### ISSUE TITLE
after the update to Unmanic 0.1.0 , it seems to not work with UNRAID anymore

### ISSUE THREAD

**Issue by PunxBS** [Unmanic/unmanic#215]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect: YES

Remember that these are some guidelines, use your best judgement.

### Description

[after the update to Unmanic 0.1.0 , it seems to not work with UNRAID anymore]

### Steps to Reproduce

1. [Update in Unraid to 0.1.0]
2. [Setting up the paths of the library]
3. [Launching the web interface]
4. [Select settings to check if HEVC options are preserved.]

**Expected behavior:** [I expected to find the same or similar settings that I found and set in the previous version]

**Actual behaviour:** [I find the settings 
- Library
- Workers
- Plugins
unfortunately no more possibility to set the codec or other things ]

**Reproduces how often:** [100%]

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
Unraid 
Version 6.9.2 2021-04-07
Base distro:
docker: version 20.10.5
fuse3: version 3.10.2
nginx: version 1.19.9
samba: verson 4.12.14 (CVE-2020-27840 CVE-2020-27840)
Linux kernel:
version 5.10.28
include all CONFIG_NF_* modules
oot: realtek r8125: version 9.005.01

Unmanic
Version - 0.1.0~cdde886

### Installation Method Used

Manually installed and run or run through Docker?

Running via Docker in Unraid

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
Since you are running this on Unraid, please refer to these posts:
- https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/?do=findComment&comment=1024811
- https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/?do=findComment&comment=1028932
- https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/?do=findComment&comment=1029421
- https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/?do=findComment&comment=1033648
- https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/?do=findComment&comment=1035113
- https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/?do=findComment&comment=1035205

Unmanic v0.1.0 does not have any FFmpeg configuration. You will need to re-configure it.

**Comment by Josh5** [comment]
Closing as there is nothing for me to do on this issue
