### ISSUE TITLE
Regex  not working to filter scanning

### ISSUE THREAD

**Issue by joelkeasley** [Unmanic/unmanic#257]
### Description

For the life of me, I can not get regex to work it ignores everything i do I have the main data folder on my server and it contains subdirectories my issue is I can not scan the main folder that contains movies, tv shows, etc without it scanning everrrrrrry thing I only need two folders I went as far as adding () on all other folders
and using your plugin I set multiple ways to achieve it not scanning .
examples 
^.*\(.*\).*\..*$
/\(([^)]+)\)/

**Expected behavior:** [What you expect to happen]
two only scan two folders

**Actual behaviour:** [What actually happens]
Scans everything

**Reproduces how often:** [What percentage of the time does it reproduce?]
100
### Versions
Version - 0.1.3+978f68f
Ubuntu server 20.04

### Installation Method Used
Docker, Portainer.io

**Comment by dalkain** [comment]
The Path Ignore plugin doesn't actually stop Unmanic from scanning matching paths, but it does make it ignore any files found that match the patterns even if other conditions would be met for them to be added to the queue. It's been a little tricky to work around on my own setup because of how slow the scanning process is, but with how useful the software is it was worth me making a minor change to the structure of the media I wanted it to process.

Your best best would probably be to run multiple containers with one pointed at your TV Shows folder and one pointed at your Movies folder.

Perhaps Josh can provide more insight into the inner workings of the scanner and this plugin in particular, but I _believe_ this is because of how the plugins (including Path Ignore) are what process the files; the library scanner itself just gathers a list of all files found in the library path and assigns them out to the plugin processes to determine what to do with them. You can confirm the plugin is working if you check your logs. You should see entries for:
`<TIMESTAMP>:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - File should be ignored because path '<FULL FILE PATH>' matches the configured regex '<REGEX ENTRY IT MATCHES>'`

**Comment by Josh5** [comment]
That explanation is pretty much spot on. 

Just some notes...
I have begun work on multi library support. And the staging branch does now have huge improvement to the library scan speed.

**Comment by joelkeasley** [comment]
Awesome glad to hear that let me know if you need a test dummy or anything
like that
