### ISSUE TITLE
Secure by username:password

### ISSUE THREAD

**Issue by IISavioII** [Unmanic/unmanic#410]
### Description

If we place in docker container is there a way to secure by username/password so that there is some protection from outside network to connect and control files / delete / rename.

### Steps to Reproduce

Password to secure the container

**Expected behavior:** 
Username/Password to access container

**Actual behaviour:** 

Able to login without security

**Reproduces how often:** 

100%

### Versions

Unmanic Version:
0.2.4~7339f8b
Python Version:
3.8.10.final.0
Platform (Operating System):
Linux 0cd61021b4d3 4.4.180+ #42962 SMP Sat Apr 8 00:14:26 CST 2023 x86_64 x86_64
Configuration Path:
/config/.unmanic/config
Logs Path:
/config/.unmanic/logs
Userdata Path:
/config/.unmanic/userdata

### Installation Method Used

Docker Synology

### Additional Information

Thanks!

**Comment by Josh5** [comment]
Please please please do NOT host Unmanic on the internet.
Yes there is many ways to put Unmanic beging a security later and I will leave that up to you to design. Consider a reverse proxy with authentication, or a VPN. Consider a firewall to allow only access from specific locations.

Unmanic is a tool designed to be run on a LAN. If I added a username and password to the app, it would give you a false sense of security that you and your internal network is safe, and I promise you, it would not be. If you are hosting any other self-hosted apps like Unmanic in a way that is publicly accessable to the internet, I cannot recommend enough that you stop doing that immediately. Just because it has a password feature, does not make it secure!
