### ISSUE TITLE
Fail on converting old low-res AVI files

### ISSUE THREAD

**Issue by FrankEBailey** [Unmanic/unmanic#429]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:
Yes

### Description

I have successfully transcoded dozens of MKV and MP4 files to X265, so my setup is definitely capable of working. However, I've now setup a library with the specific intent of transcoding my large collection of 80s sitcom AVI files to mp4 or MKV in X265 format. When attempting to do so, I encounter the following error on all AVI files I've tried:

```
[rawvideo @ 06a80740] Packet too small (186)
Error while decoding stream #0:0: Invalid data found when processing input
[rawvideo @ 06a80740] Packet too small (39)
Error while decoding stream #0:0: Invalid data found when processing input
```
(full error log attached below)

My FFMPEG command is:
`ffmpeg -hide_banner -loglevel info -i F:\incomplete\unmanic_file_conversion-mdavb-1694332890\Family Ties s02e06 Speed Trap-mdavb-1694332890-WORKING-1-1.avi -strict -2 -max_muxing_queue_size 2048 -map 0:v:0 -map 0:a:0 -c:v:0 libx265 -preset medium -crf 23 -c:a:0 copy -y F:\incomplete\unmanic_file_conversion-mdavb-1694332890\Family Ties s02e06 Speed Trap-mdavb-1694332890-WORKING-2-1.avi`

I have a GTX1050Ti with 4gb of vram.

The file referenced above can be downloaded here: https://drive.google.com/file/d/11kT7HB_1Y8zQF1R7IsH62-HB5FdRsgH4/view?usp=sharing , however all 320x200 or 320x240 AVI files I've tried have had the same result.

**Expected behavior:** 
A successful transcode

**Actual behaviour:** 
Transcoding fails with the above error

**Reproduces how often:** 
100% of the time according to my tests of AVI files

### Versions
Running Version: 0.2.4~7339f8b on Windows 10 using Desktop Launcher

[errorlog.txt](https://github.com/Unmanic/unmanic/files/12567858/errorlog.txt)

**Comment by austinsr1** [comment]
Could you provide a ffprobe one of the files that you are having issues processing?
What I think might have happened is you went to convert the videos and had the "keep same container" option checked in one of the encoders. This can result in a similar message to "[rawvideo @ 06a80740]". 

This issue is hevc cannot be stored in a .avi file, so it leads the file to being unplayable. There is a quick fix for these files if that is what has happened.  If you move the affected .avi files into the same directory and run this command, it will remux the files back to working order. https://github.com/Unmanic/unmanic-documentation/wiki/Help,-I-kept-the-same-container-for-avi

If you would like to open a support message in Discord, I can assist if needed. Ping @austinsr when you do, if you could.

**Comment by FrankEBailey** [comment]
I checked whether the "keep same container" setting was active, and it was! That solved the issue... now if only I could work out why AVI files transcoded to MKVs in X265 are somehow coming out larger than the original AVIs and therefore being rejected by my workflow....
