### ISSUE TITLE
Worker will not convert audio in an existing mkv when container output is mkv [bug]

### ISSUE THREAD

**Issue by the1poet** [Unmanic/unmanic#90]
### Description
Worker will not convert audio in an existing mkv when conainer output is mkv and other certain settings are selected.

### Steps to Reproduce
Settings that produce this problem:
- Output container set to mkv
- Video encoding is disabled
- Enable Audio Encoding is selected
- Enabled Audio Stream Transcoding is selected
- Audio Codec is AC-3

**Expected behavior:**
The worker would mux the mkv file to a new mkv file keeping the video, and convert the audio to ac3

**Actual behaviour:**
The worker ignores the file.

**Reproduces how often:**
Every time

### Versions
Version - v0.0.1-beta7~0be090f 

### Installation Method Used
Docker in unRAID 6.8.0 rc5

### Additional Information
If I use the same settings, but enable video encoding and set to H265, it will process the video file.

**Comment by Josh5** [comment]
So the conversion check is only running against the container and video codec. We will need to add support to run a check against the audio codec also.

**Comment by ottodoesntknow** [comment]
I was going crazy thinking of the reason why my whole library was being ignored (I only have Audio Encoding enabled). Hope this is fixed soon!

**Comment by Schnazzy** [comment]
I think this got fixed in an update yesterday.  I'm currently showing "Version - 0.0.1+5868b25".  Unmanic started adding AAC stereo tracks to all of the files I have it watching even though they are already H.265, which is how I have it set and exactly what I hoped it would start doing when this got fixed.

**Comment by ottodoesntknow** [comment]
Tried the most recent Docker build to see if this was finally fixed but I'm still getting this bug, Unmanic things everything is perfect with my media, but they lack the stereo track.

**Comment by Josh5** [comment]
> Tried the most recent Docker build to see if this was finally fixed but I'm still getting this bug, Unmanic things everything is perfect with my media, but they lack the stereo track.

I believe the stereo conversions will be removed as a feature in an upcoming release. This will be in favour of a plugin to do the same thing but with the ability to test files during the scan process to determine if a file needs to be processed.

Unmanic does not have the ability to test if stereo copies of multi-channel streams already exist. Unmanic would not be able to determine if that stereo stream is a copy or its own unrelated stream. Adding such a feature to Unmanic is costly and for these reasons this particular issue of yours will likely never be fixed by myself. Moving this process of generating stereo stream copies to the plugin system will allow much easier development of the file testing side of things.

**Comment by Josh5** [comment]
This original bug was to enable audio only conversions. Unmanic now has the ability to do this by unselecting the video conversion checkbox and by selecting to keep the original file container.

As such I'm closing this issue and marking it as fixed.
